export const bus = [
    {
        "busId": "1",
        "price": 10,
        "category": "government",
        "busGateway": "Gateway A",
        "busLogo": "https://i.ibb.co/RYB682P/emirateslogo.png",
        "busName": "Government Bus",
        "currentDestination": "Chennai",
        "busInterval": "30 minutes",
        "nextDestination": "Mumbai",
        "departureTime": "6:00 PM",
        "arrivalTime": "8:00 PM",
        "busDuration": "2 hours",
        "adultPrice": 10.00,
        "childrenPrice": 5.00,
        "infantPrice": 0.00,
        "routeNameFrom": "CHE",
        "routeNameTo": "MUM",
        "busCompanyName": "Express J"
    },
    {
        "busId": "11",
        "price": 20,
        "category": "government",
        "busGateway": "Gateway A",
        "busLogo": "https://i.ibb.co/RYB682P/emirateslogo.png",
        "busName": "Government Bus",
        "currentDestination": "Chennai",
        "busInterval": "30 minutes",
        "nextDestination": "Mumbai",
        "departureTime": "6:00 PM",
        "arrivalTime": "8:00 PM",
        "busDuration": "2 hours",
        "adultPrice": 10.00,
        "childrenPrice": 5.00,
        "infantPrice": 0.00,
        "routeNameFrom": "CHE",
        "routeNameTo": "MUM",
        "busCompanyName": "Bambooflat Express"
    },
    {
        "busId": "2",
        "price": 40,
        "category": "government",
        "busGateway": "Gateway A",
        "busLogo": "https: //i.ibb.co/RYB682P/emirateslogo.png",
        "busName": "Government Bus",
        "currentDestination": "Mumbai",
        "busInterval": "30 minutes",
        "nextDestination": "Port Blair",
        "departureTime": "12:00 PM",
        "arrivalTime": "2:00 PM",
        "busDuration": "2 hours",
        "adultPrice": 10.00,
        "childrenPrice": 5.00,
        "infantPrice": 0.00,
        "routeNameFrom": "MUM",
        "routeNameTo": "PORT BLAIR(PBL)",
        "busCompanyName": "Anand"
    },
    {
        "busId": "3",
        "price": 40,
        "category": "government",
        "busGateway": "Gateway A",
        "busLogo": "https://i.ibb.co/RYB682P/emirateslogo.png",
        "busName": "Government Bus",
        "currentDestination": "Chennai",
        "busInterval": "30 minutes",
        "nextDestination": "Port Blair",
        "departureTime": "7:00 PM",
        "arrivalTime": "9:00 PM",
        "busDuration": "2 hours",
        "adultPrice": 10.00,
        "childrenPrice": 5.00,
        "infantPrice": 0.00,
        "routeNameFrom": "CHE",
        "routeNameTo": "PORT BLAIR(PBL)",
        "busCompanyName": "Express D2"
    },
    {
        "busId": "4",
        "price": 60,
        "category": "government",
        "busGateway": "Gateway A",
        "busLogo": "https://i.ibb.co/RYB682P/emirateslogo.png",
        "busName": "Government Bus",
        "currentDestination": "Port Blair",
        "busInterval": "30 minutes",
        "nextDestination": "Mumbai",
        "departureTime": "2:00 PM",
        "arrivalTime": "4:00 PM",
        "busDuration": "2 hours",
        "adultPrice": 10.00,
        "childrenPrice": 5.00,
        "infantPrice": 0.00,
        "routeNameFrom": "PORT BLAIR(PBL)",
        "routeNameTo": "MUM",
        "busCompanyName": "Express D2"
    },
    {
        "busId": "13",
        "price": 30,
        "category": "private",
        "busGateway": "Gateway A",
        "busLogo": "https://i.ibb.co/RYB682P/emirateslogo.png",
        "busName": "Private Bus",
        "currentDestination": "Chennai",
        "busInterval": "30 minutes",
        "nextDestination": "Mumbai",
        "departureTime": "2:00 PM",
        "arrivalTime": "4:00 PM",
        "busDuration": "2 hours",
        "adultPrice": 10.00,
        "childrenPrice": 5.00,
        "infantPrice": 0.00,
        "routeNameFrom": "CHE",
        "routeNameTo": "MUM",
        "busCompanyName": "Express D2"
    },
    {
        "busId": "15",
        "price": 30,
        "category": "private",
        "busGateway": "Gateway A",
        "busLogo": "https://i.ibb.co/RYB682P/emirateslogo.png",
        "busName": "Private Bus",
        "currentDestination": "Port Blair",
        "busInterval": "30 minutes",
        "nextDestination": "Mumbai",
        "departureTime": "2: 00 PM",
        "arrivalTime": "4: 00 PM",
        "busDuration": "2 hours",
        "adultPrice": 10.00,
        "childrenPrice": 5.00,
        "infantPrice": 0.00,
        "routeNameFrom": "PORT BLAIR(PBL)",
        "routeNameTo": "MUM",
        "busCompanyName": "Express D2"
    },
    {
        "busId": "22",
        "price": 230,
        "category": "private",
        "busGateway": "Gateway A",
        "busLogo": "https://i.ibb.co/RYB682P/emirateslogo.png",
        "busName": "Private Bus",
        "currentDestination": "Port Blair",
        "busInterval": "30 minutes",
        "nextDestination": "Mumbai",
        "departureTime": "2: 00 PM",
        "arrivalTime": "4:00 PM",
        "busDuration": "2 hours",
        "adultPrice": 10.00,
        "childrenPrice": 5.00,
        "infantPrice": 0.00,
        "routeNameFrom": "PORT BLAIR(PBL)",
        "routeNameTo": "MUM",
        "busCompanyName": "Express D2"
    },
    {
        "busId": "27",
        "price": 230,
        "category": "private",
        "busGateway": "Gateway A",
        "busLogo": "https://i.ibb.co/RYB682P/emirateslogo.png",
        "busName": "Private Bus",
        "currentDestination": "Mumbai",
        "busInterval": "30 minutes",
        "nextDestination": "Chennai",
        "departureTime": "2:00 PM",
        "arrivalTime": "4:00 PM",
        "busDuration": "2 hours",
        "adultPrice": 10.00,
        "childrenPrice": 5.00,
        "infantPrice": 0.00,
        "routeNameFrom": "MUM",
        "routeNameTo": "CHE",
        "busCompanyName": "Express D2"
    },
    {
        "busId": "21",
        "price": 230,
        "category": "private",
        "busGateway": "Gateway A",
        "busLogo": "https://i.ibb.co/RYB682P/emirateslogo.png",
        "busName": "Private Bus",
        "currentDestination": "Chennai",
        "busInterval": "30 minutes",
        "nextDestination": "Mumbai",
        "departureTime": "2:00 PM",
        "arrivalTime": "4:00 PM",
        "busDuration": "2 hours",
        "adultPrice": 10.00,
        "childrenPrice": 5.00,
        "infantPrice": 0.00,
        "routeNameFrom": "CHE ",
        "routeNameTo": "MUM",
        "busCompanyName": "Express D2"
    },
    {
        "busId": "21",
        "price": 230,
        "category": "private",
        "busGateway": "Gateway A",
        "busLogo": "https://i.ibb.co/RYB682P/emirateslogo.png",
        "busName": "Private Bus",
        "currentDestination": "Chennai",
        "busInterval": "30 minutes",
        "nextDestination": "Port Blair",
        "departureTime": "2:00 PM",
        "arrivalTime": "4:00 PM",
        "busDuration": "2 hours",
        "adultPrice": 10.00,
        "childrenPrice": 5.00,
        "infantPrice": 0.00,
        "routeNameFrom": "CHE ",
        "routeNameTo": "PORT BLAIR(PBL)",
        "busCompanyName": "Express D2"
    }
]